version: '2.4'

services:
  mongo:
    image: mongo
    restart: always
    container_name: key-mongo
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    restart: always
    container_name: key-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  redis:
    image: redis
    restart: always
    container_name: key-redis
    ports:
      - 6379:6379